[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Admin panel redirects
[[redirects]]
  from = "/admin"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/index.html"
  status = 200

# Auth page redirects
[[redirects]]
  from = "/auth"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/auth/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Handle client-side routing
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block" 