// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://owmvzsmxjdasrzobgjti.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93bXZ6c214amRhc3J6b2JnanRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNDA0MDksImV4cCI6MjA2OTgxNjQwOX0.IVdqlyPt0fFCYo_cPVuZDrKkGFqMdSNG8uMGM9i-ItY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

